---
kind: pipeline
type: exec
name: default

platform:
  os: windows
  arch: amd64

trigger:
  refs: 
  - refs/heads/**

environment:
  NPM_TOKEN:
    from_secret: NPM_TOKEN

steps:
- name: Install packages with yarn
  commands:
  - yarn --frozen-lockfile

- name: Run unit tests
  commands:
  - yarn test:unit

- name: Build
  commands:
  - yarn build