---
kind: pipeline
type: exec
name: Continuous Integration Pipeline

platform:
  os: windows
  arch: amd64

trigger:
  refs: 
  - refs/heads/v*
  branch:
  - main

steps:
- name: Install packages with yarn
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn --frozen-lockfile

- name: Run unit tests
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn test:unit

- name: Build
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn build

- name: Semantic Release
  when:
    branch:
      - main
  commands:
  - yarn semantic-release
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN

  
---
kind: pipeline
name: Continuous Deployment
type: docker
trigger:
  branch:
  - deployment
steps:
  - name: test
    image: node
    commands:
    - npm install
  # - name: check ansible syntax
  #   image: plugins/ansible:3
  #   settings:
  #     playbook: ansible/main.yml
  #     inventory: ansible/inventory.yml
  #     syntax_check: true