kind: pipeline
type: exec
name: continuous-integration

platform:
  os: windows
  arch: amd64

trigger:
  branch:
  - main
  - monorepo
  ref:
    exclude:
      - refs/tags/*

steps:
# - name: update tools
#   commands:
#     - npm install -g npm@9.6.0
#     - npm install -g 'yarn@1.22.19'

- name: Check version of tools
  commands:
  - node -v
  - npm -v
  - yarn -v


- name: Install packages with yarn
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn --frozen-lockfile

- name: Run unit tests
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - npx nx test home-file-service

- name: Build
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - npx nx build home-file-service  

- name: Semantic Release
  commands:
  - npx nx run home-file-service:semantic-release 
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN

# ---
# kind: pipeline
# name: continuous-deployment
# type: docker

# platform:
#   os: linux
#   arch: arm64

# trigger:
#   ref: 
#     - refs/tags/v*
    
# steps:
#   - name: Run ansible deployment playbook
#     image: plugins/ansible:3
#     settings:
#       playbook: ansible/main.yml
#       inventory: ansible/inventory.yml
#       vault_password:
#         from_secret: ansible_vault_pass
#       requirements: ansible/requirements.txt
#       extra_vars: DRONE_COMMIT_REF=${DRONE_COMMIT_REF}