kind: pipeline
type: exec
name: continuous-integration

platform:
  os: windows
  arch: amd64

trigger:
  branch:
  - main
  ref:
    exclude:
      - refs/tags/*

steps:
- name: Install packages with yarn
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn --frozen-lockfile

- name: Run unit tests
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn test:unit

- name: Build
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn build

- name: Semantic Release
  commands:
  - yarn semantic-release
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN

---
kind: pipeline
name: continuous-deployment
type: docker

platform:
  os: linux
  arch: arm64

trigger:
  ref: 
    - refs/tags/v*
    
steps:
  - name: Run ansible deployment playbook
    image: plugins/ansible:3
    settings:
      playbook: ansible/main.yml
      inventory: ansible/inventory.yml
      vault_password:
        from_secret: ansible_vault_pass
      requirements: ansible/requirements.txt
      extra_vars: DRONE_COMMIT_REF=${DRONE_COMMIT_REF}