---
kind: pipeline
type: exec
name: default

platform:
  os: windows
  arch: amd64

trigger:
  refs: 
  - refs/heads/**

steps:
- name: Install packages
  commands:
  - yarn --frozen-lockfile
- name: Run tests
  commands:
  - yarn test