---
kind: pipeline
type: exec
name: default

platform:
  os: windows
  arch: amd64

trigger:
  refs: 
  - refs/heads/**

- name: Install packages with yarn
  commands:
  - yarn --frozen-lockfile

- name: Run tests
  commands:
  - yarn test