kind: pipeline
type: exec
name: continuous-integration
platform:
  os: windows
  arch: amd64
node:
  name: elder_wand

trigger:
  branch:
  - main
  ref:
    exclude:
      - refs/tags/*

steps:
- name: Install packages with yarn
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn --frozen-lockfile

- name: Run unit tests
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - npx nx test home-file-service

- name: Build
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - npx nx build home-file-service  

- name: Semantic Release
  commands:
  - npx nx run home-file-service:semantic-release 
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN

---
kind: pipeline
name: stop-service
type: exec
platform:
  os: windows
  arch: amd64
node:
  name: elder_wand
trigger:
  ref: 
    - refs/tags/v*
  # branch:
  #   - main
steps:
  - name: "Stop Service"
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
    - npm install -g node-windows
    - cd packages/service-installer
    - npm link node-windows
    - npm run stop

---
kind: pipeline
name: update-files
type: docker

platform:
  os: linux
  arch: arm64
depends_on:
  - stop-service
steps:
  - name: Run ansible deployment playbook
    image: plugins/ansible:3
    settings:
      playbook: ansible/main.yml
      inventory: ansible/inventory.yml
      vault_password:
        from_secret: ansible_vault_pass
      requirements: ansible/requirements.txt
      extra_vars: DRONE_COMMIT_REF=${DRONE_COMMIT_REF}

---
kind: pipeline
name: start-service
type: exec
platform:
  os: windows
  arch: amd64
node:
  name: elder_wand
depends_on:
  - update-files
steps:
- name: "Install & Start New Service"
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - npm install -g node-windows
  - cd packages/service-installer
  - npm link node-windows
  - npm run install
