---
kind: pipeline
type: exec
name: default

platform:
  os: windows
  arch: amd64

trigger:
  refs: 
  - refs/heads/**

steps:
- name: Install packages with yarn
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn --frozen-lockfile

- name: Run unit tests
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn test:unit

- name: Build
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn build

- name: Semantic Release
  when:
    branch:
      - main
  commands:
  - yarn semantic-release
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN

  
