kind: pipeline
type: exec
name: continuous-integration

platform:
  os: windows
  arch: amd64

node:
  name: elder_wand

trigger:
  branch:
  - main
  - monorepo
  ref:
    exclude:
      - refs/tags/*

steps:
- name: Install packages with yarn
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - yarn --frozen-lockfile

- name: Run unit tests
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - npx nx test home-file-service

- name: Build
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  commands:
  - npx nx build home-file-service  

- name: Semantic Release
  commands:
  - npx nx run home-file-service:semantic-release 
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN

---
kind: pipeline
name: deployment 
type: exec

platform:
  os: windows
  arch: amd64

node:
  name: elder_wand

trigger:
  ref: 
    - refs/tags/v*
  event:
    - promote
  
steps:
  - name: "Un-install previous"
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
    - yarn link node-windows
    - npx nx run service-installer:stop
# steps:
#   - name: Run ansible deployment playbook
#     image: plugins/ansible:3
#     settings:
#       playbook: ansible/main.yml
#       inventory: ansible/inventory.yml
#       vault_password:
#         from_secret: ansible_vault_pass
#       requirements: ansible/requirements.txt
#       extra_vars: DRONE_COMMIT_REF=${DRONE_COMMIT_REF}