---
kind: pipeline
type: exec
name: default

platform:
  os: windows
  arch: amd64

trigger:
  refs: 
  - refs/heads/**

steps:
- name: Install packages with yarn
  environment:
    NPM_TOKEN:
      from_secret: GH_TOKEN
  commands:
  - yarn --frozen-lockfile


- name: Run unit tests
  commands:
  - yarn test:unit

- name: Build
  commands:
  - yarn build