default:
  gameClipConfig:
    outputDirectory: '\\RoomOfRequirement\Video Editing\GameCaptures\Raw'
    gameClipMoveConfig:
      copyMode: true
  logging:
    level: info
    colorize: false
  port: 4000