
- name: Test connectivity
  hosts: elder_wand
  vars:
    DRONE_COMMIT_REF: 'refs/tags/v1.1.5'
    temp_dir: "C:\\temp"
    app_dir: "C:\\home-file-service"
    app_version: "{{ DRONE_COMMIT_REF | regex_replace('refs/tags/v') }}"
  tasks:
    - name: Remove temporary files
      ansible.windows.win_file:
        path: "{{temp_dir}}\\package"
        state: absent
    
    - name: Firewall rule to allow HTTP on TCP port 4000
      community.windows.win_firewall_rule:glk
        name: HTTP
        localport: 4000
        action: allow
        direction: in
        protocol: tcp
        profiles: private
        state: present
        enabled: yes

    # - name: touch temp file
    #   ansible.windows.win_file:
    #     path: "{{temp_dir}}\\file.txt"
    #     state: touch

    # - name: Insert line into file
    #   community.windows.win_lineinfile:
    #     path: "{{temp_dir}}\\file.txt"
    #     line: "npm pack home-file-service@v{{app_version}}"

    - name: Restore package version from verdaccio
      ansible.windows.win_shell: "npm pack home-file-service@v{{app_version}}"
      args:
        chdir: "{{temp_dir}}"
    
    - name: Un tar/gz the packed file in the temp dir
      ansible.windows.win_shell: "tar -xvzf  {{temp_dir}}\\home-file-service-{{app_version}}.tgz"
      args:
        chdir: "{{temp_dir}}"

    - name: Retrieve node modules
      ansible.windows.win_shell: "npm install"
      args:
        chdir: "{{temp_dir}}\\package"

    - name: npm link node-windows
      ansible.windows.win_shell: "npm link node-windows"
      args:
        chdir: "{{temp_dir}}\\package"

    - name: Stop the existing service.
      ansible.windows.win_shell: "npm run service:stop"
      args:
        chdir: "{{temp_dir}}\\package"

    - name: Delete home-file-service directory
      ansible.windows.win_file:
        path: "{{app_dir}}"
        state: absent

    - name: Create home-file-service directory
      ansible.windows.win_file:
        path: "{{app_dir}}"
        state: directory

    - name: Copy latest package folder into home-file-service
      ansible.windows.win_copy:
        src: "{{temp_dir}}\\package"
        dest: "{{app_dir}}"
        remote_src: yes
  
    - name: Copy the config file to remote
      ansible.windows.win_copy:
        src: "./files/config.yml"
        dest: "{{app_dir}}\\package"

    - name: Install the service.
      ansible.windows.win_shell: "npm run service:install"
      args:
        chdir: "{{temp_dir}}\\package"