
- name: Test connectivity
  hosts: elder_wand
  vars:
    DRONE_COMMIT_REF: 'refs/tags/v1.0.8'
    temp_dir: "C:\\temp"
    app_dir: "C:\\home-file-service"
    app_version: "{{ DRONE_COMMIT_REF | regex_replace('refs/tags/v') }}"
  tasks:
    - name: Remove temporary files
      ansible.windows.win_file:
        path: "{{temp_dir}}\\package"
        state: absent
    
    - name: Create home-file-service directory
      ansible.windows.win_file:
        path: "{{app_dir}}"
        state: directory

    - name: Restore package version from verdaccio
      ansible.windows.win_shell: "npm pack home-file-service@v{{app_version}}"
      args:
        chdir: "{{app_dir}}"
    
    - name: Un tar/gz the packed file in the temp dir
      ansible.windows.win_shell: "tar -xvzf  {{temp_dir}}\\home-file-service-{{app_version}}.tgz"
      args:
        chdir: "{{app_dir}}"
